language: node_js
node_js:
  - "7"
install:
  - npm install
  - npm run build
script:
  - echo '111'
  - ls -l dist
  - - chmod 600 ./identity/
  - scp -i ./identity/WebGisKey -r ./dist/static root@115.159.65.170:/home/nginx
  - scp -i ./identity/WebGisKey  ./dist/index.html root@115.159.65.170:/home/nginx

